import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  header: {
    paddingTop: 52,
    paddingBottom: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    width: 180,
    height: 180,
    borderRadius: 90,
    backgroundColor: 'rgba(255,255,255,0.08)',
    top: -50,
    right: -30,
  },
  headerContent: { flexDirection: 'row', alignItems: 'center' },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerTitle: { fontSize: 18, fontWeight: '800', color: '#fff' },
  headerSub: { fontSize: 12, color: 'rgba(255,255,255,0.8)' },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  filters: { padding: 12, gap: 8 },
  filterRow: { flexDirection: 'row', gap: 10 },
  list: { paddingHorizontal: 14, paddingBottom: 32, gap: 12 },

  card: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ede9fe',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: { fontSize: 16, fontWeight: '700', color: '#7c3aed' },
  studentName: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  studentMeta: { fontSize: 12, color: '#64748b', marginTop: 1 },
  progressWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  progressBg: {
    flex: 1,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e2e8f0',
  },
  progressFill: { height: 6, borderRadius: 3 },
  pctText: { fontSize: 12, fontWeight: '700', minWidth: 36 },
  amountsRow: { flexDirection: 'row', marginBottom: 8 },
  amountItem: { flex: 1, alignItems: 'center' },
  amountLabel: { fontSize: 11, color: '#94a3b8', fontWeight: '500' },
  amountValue: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
    marginTop: 2,
  },
  overdueTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fef2f2',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  overdueText: { fontSize: 11, color: '#dc2626', fontWeight: '600' },
  refundInfoTag: {
    marginTop: 8,
    borderRadius: 8,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#fed7aa',
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  refundInfoText: {
    fontSize: 11,
    color: '#c2410c',
    fontWeight: '600',
  },
  cardActions: {
    flexDirection: 'row',
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  actionText: { fontSize: 12, fontWeight: '600' },

  // Hoisted (RN CLI no-inline-styles)
  cardTitleWrap: { flex: 1, marginLeft: 10 },
  headerTextWrap: { flex: 1, marginLeft: 8 },
  flex1: { flex: 1 },
  amountValueGreen: { color: '#059669' },
  actionBtnOrange: { backgroundColor: '#fff7ed' },
  actionTextOrange: { color: '#ea580c' },
  actionBtnGreen: { backgroundColor: '#f0fdf4' },
  actionTextGreen: { color: '#059669' },
  actionBtnBlue: { backgroundColor: '#eff6ff' },
  actionTextBlue: { color: '#3b82f6' },
  actionBtnViolet: { backgroundColor: '#f5f3ff' },
  actionTextViolet: { color: '#7c3aed' },
  actionTextCyan: { color: '#0284c7' },
  actionBtnGrayAuto: { backgroundColor: '#f8fafc', marginLeft: 'auto' },
  actionTextGray: { color: '#64748b' },
});
