import { StyleSheet } from 'react-native';

export const marksStyles = StyleSheet.create({
  body: { flex: 1, backgroundColor: '#f8fafc' },
  bodyContent: { padding: 16, paddingBottom: 40 },

  spacer: { width: 40 },
  flex1: { flex: 1 },
  emojiIcon: { fontSize: 16 },

  statsRow: { flexDirection: 'row', gap: 8, marginBottom: 20 },
  statCard: {
    flex: 1,
    alignItems: 'center',
    padding: 12,
    borderRadius: 14,
    gap: 4,
  },
  statCardBlue: { backgroundColor: '#eff6ff' },
  statCardGreen: { backgroundColor: '#dcfce7' },
  statCardRed: { backgroundColor: '#fee2e2' },
  statCardViolet: { backgroundColor: '#f5f3ff' },
  statValue: { fontSize: 20, fontWeight: '800' },
  statValueBlue: { color: '#2563eb' },
  statValueGreen: { color: '#16a34a' },
  statValueRed: { color: '#dc2626' },
  statValueViolet: { color: '#7c3aed' },
  statLabel: { fontSize: 10, color: '#64748b', fontWeight: '600' },

  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 10,
    marginTop: 8,
  },

  /* Subject card */
  subjectCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  subjectHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  subjectName: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  subjectMax: { fontSize: 12, color: '#94a3b8' },
  barRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  barLabel: { fontSize: 11, color: '#94a3b8', width: 30 },
  barContainer: { flex: 1 },
  barTrack: { height: 8, borderRadius: 4, overflow: 'hidden' },
  barTrackBlue: { backgroundColor: '#eff6ff' },
  barFill: { height: '100%', borderRadius: 4 },
  barFillBlue: { backgroundColor: '#3b82f6' },
  barValue: {
    fontSize: 12,
    fontWeight: '700',
    minWidth: 30,
    textAlign: 'right',
  },
  barValueBlue: { color: '#3b82f6' },
  subjectStats: { flexDirection: 'row', gap: 6, marginTop: 6 },
  chip: {
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    overflow: 'hidden',
  },
  chipGreen: { backgroundColor: '#dcfce7', color: '#16a34a' },
  chipRed: { backgroundColor: '#fee2e2', color: '#dc2626' },
  chipAmber: { backgroundColor: '#fef3c7', color: '#d97706' },

  /* Student card */
  studentCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  studentHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  studentName: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  studentAdm: { fontSize: 12, color: '#94a3b8', marginTop: 2 },
  passBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  passText: { fontSize: 11, fontWeight: '800' },

  /* Marks bar section */
  marksBarSection: { gap: 8, marginBottom: 10 },
  markBarRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  markBarSubject: { fontSize: 11, color: '#64748b', width: 70 },
  absentBar: {
    flex: 1,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#fef3c7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  absentText: { fontSize: 8, fontWeight: '800', color: '#d97706' },
  noMark: { fontSize: 12, color: '#cbd5e1' },

  /* Summary */
  summarySection: {
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 10,
    marginTop: 4,
  },
  summaryBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  summaryLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: '#1e293b',
    width: 70,
  },
  percentageRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  percentageText: { fontSize: 13, color: '#64748b', fontWeight: '600' },
  percentBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 8 },
  percentBadgeText: { fontSize: 13, fontWeight: '800' },

  loading: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  loadingText: { fontSize: 14, color: '#64748b', marginTop: 12 },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  emptyIcon: { fontSize: 48, marginBottom: 12 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: '#334155' },
  emptySubtitle: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    paddingHorizontal: 32,
    marginTop: 6,
  },
});
