import { StyleSheet } from 'react-native';

export const st = StyleSheet.create({
  saveHeaderBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#94a3b8',
    letterSpacing: 0.5,
    marginBottom: 8,
    marginTop: 12,
  },
  mt16: { marginTop: 16 },
  addLunchText: { color: '#d97706' },
  dimmed: { opacity: 0.6 },
  // Day selector chips
  dayRow: { gap: 6, paddingBottom: 4 },
  dayChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  dayChipActive: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  dayChipConfigured: {
    borderColor: '#22c55e',
    backgroundColor: '#f0fdf4',
  },
  dayChipText: { fontSize: 12, fontWeight: '700', color: '#64748b' },
  dayChipTextActive: { color: '#fff' },
  dayChipTextConfigured: { color: '#16a34a' },
  configuredDot: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#22c55e',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Also Save To chips
  alsoSaveHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 12,
  },
  quickLink: { fontSize: 11, fontWeight: '600', color: '#7c3aed' },
  saveChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#fff',
  },
  saveChipEditing: {
    backgroundColor: '#f5f3ff',
    borderColor: '#c4b5fd',
  },
  saveChipSelected: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  saveChipText: { fontSize: 11, fontWeight: '600', color: '#94a3b8' },
  saveChipTextEditing: { color: '#7c3aed' },
  saveChipTextSelected: { color: '#fff' },
  // Copy from chips
  copyChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f5f3ff',
    borderWidth: 1,
    borderColor: '#c4b5fd',
  },
  copyChipText: { fontSize: 11, fontWeight: '600', color: '#7c3aed' },
  // Slot card
  slotCard: {
    borderRadius: 14,
    padding: 12,
    borderLeftWidth: 4,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 2,
  },
  slotTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  typeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  typeText: { fontSize: 10, fontWeight: '700' },
  labelInput: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    paddingVertical: 2,
    paddingHorizontal: 6,
    backgroundColor: 'rgba(255,255,255,0.6)',
    borderRadius: 6,
  },
  deleteBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: 'rgba(220,38,38,0.08)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // Inline type picker
  typePicker: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginBottom: 8,
    padding: 8,
    backgroundColor: '#fff',
    borderRadius: 10,
  },
  typeOption: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  typeOptionActive: {
    backgroundColor: '#7c3aed',
    borderColor: '#7c3aed',
  },
  typeOptionText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  typeOptionTextActive: { color: '#fff' },
  // Time row
  timeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  timeField: { flex: 1 },
  timeLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: '#94a3b8',
    marginBottom: 2,
  },
  timeInput: {
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    fontSize: 14,
    fontWeight: '600',
    color: '#1e293b',
    textAlign: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
  },
  timeArrow: {
    fontSize: 16,
    fontWeight: '700',
    color: '#94a3b8',
    marginTop: 12,
  },
  timePreview: {
    fontSize: 10,
    fontWeight: '500',
    marginTop: 12,
    flexShrink: 1,
  },
  // Add buttons
  addBtnRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    marginBottom: 8,
  },
  addPeriodBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#eff6ff',
    borderWidth: 1.5,
    borderColor: '#93c5fd',
    borderStyle: 'dashed',
    paddingVertical: 12,
    borderRadius: 12,
  },
  addPeriodText: { fontSize: 13, fontWeight: '600', color: '#2563eb' },
  addBreakBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: '#f0fdf4',
    borderWidth: 1.5,
    borderColor: '#86efac',
    borderStyle: 'dashed',
    paddingVertical: 12,
    borderRadius: 12,
  },
  addBreakText: { fontSize: 13, fontWeight: '600', color: '#16a34a' },
  // Action buttons
  actionRow: { gap: 10, marginTop: 16 },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#7c3aed',
    paddingVertical: 14,
    borderRadius: 12,
  },
  primaryBtnText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  clearBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: '#fee2e2',
    paddingVertical: 12,
    borderRadius: 12,
  },
  clearBtnText: { fontSize: 14, fontWeight: '600', color: '#dc2626' },
});
