import { Colors } from '@educard/shared';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // Hoisted inline-style helpers
  statTextBlue: { color: '#3b82f6' },
  statTextGreen: { color: '#10b981' },
  actionBtnTextAmber: { color: '#f59e0b' },
  actionBtnTextRed: { color: '#ef4444' },
  actionBtnTextWhite: { color: '#fff' },
  dateBadgeTextWhite: { color: '#fff' },
  statValueGreen: { color: '#10b981' },
  statValueBlue: { color: '#3b82f6' },
  statValueAmber: { color: '#f59e0b' },
  mt8: { marginTop: 8 },
  ml8: { marginLeft: 8 },

  classSelector: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  classLoadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    gap: 8,
  },
  classLoadingText: {
    fontSize: 14,
    color: Colors.gray[500],
  },
  noClassesContainer: {
    paddingVertical: 12,
  },
  noClassesText: {
    fontSize: 14,
    color: Colors.gray[500],
    textAlign: 'center',
  },
  classDropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.gray[50],
    borderWidth: 1,
    borderColor: Colors.gray[200],
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  classDropdownContent: {
    flex: 1,
  },
  classDropdownLabel: {
    fontSize: 12,
    color: Colors.gray[500],
    marginBottom: 2,
  },
  classDropdownValue: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  classDropdownText: {
    fontSize: 16,
    fontWeight: '600',
    color: Colors.gray[800],
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '70%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: Colors.gray[800],
  },
  modalList: {
    paddingVertical: 8,
  },
  modalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[50],
  },
  modalItemSelected: {
    backgroundColor: Colors.primary[50],
  },
  modalItemContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  modalItemText: {
    fontSize: 16,
    color: Colors.gray[700],
  },
  modalItemTextSelected: {
    fontWeight: '600',
    color: Colors.primary[600],
  },
  ctBadge: {
    marginLeft: 6,
    backgroundColor: '#fbbf24',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  ctBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#78350f',
  },
  dateNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  dateNavBtn: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: Colors.gray[100],
  },
  dateNavBtnDisabled: {
    opacity: 0.5,
  },
  dateDisplay: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dateText: {
    fontSize: 15,
    fontWeight: '600',
    color: Colors.gray[800],
  },
  dateBadge: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 10,
    backgroundColor: Colors.gray[200],
  },
  dateBadgeText: {
    fontSize: 10,
    fontWeight: '600',
    color: Colors.gray[600],
  },
  statsBar: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  notificationSection: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  notificationBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#eff6ff',
    borderWidth: 1,
    borderColor: '#bfdbfe',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  notificationBannerText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 18,
    color: '#1e40af',
  },
  sendNotificationBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary[500],
    borderRadius: 10,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  sendNotificationBtnDisabled: {
    opacity: 0.7,
  },
  sendNotificationBtnText: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
  },
  statValue: {
    fontSize: 20,
    fontWeight: '700',
    color: Colors.gray[800],
  },
  statLabel: {
    fontSize: 11,
    color: Colors.gray[500],
  },
  listContent: {
    padding: 16,
    paddingBottom: 100,
  },
  subjectCard: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  subjectHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  subjectIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  subjectInfo: {
    flex: 1,
    marginLeft: 10,
  },
  subjectName: {
    fontSize: 15,
    fontWeight: '700',
  },
  teacherName: {
    fontSize: 12,
    color: Colors.gray[500],
    marginTop: 1,
  },
  teacherBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  teacherBadgeText: {
    fontSize: 11,
    fontWeight: '600',
  },
  homeworkContent: {
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
  },
  homeworkTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.gray[800],
    marginBottom: 8,
  },
  homeworkMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  metaItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  metaText: {
    fontSize: 12,
    color: Colors.gray[500],
  },
  statusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
  },
  statusText: {
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  statsRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
  },
  statItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  statText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.gray[600],
  },
  actionsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  actionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Colors.primary[50],
  },
  submissionsBtn: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: Colors.primary[500],
  },
  actionBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.primary[500],
  },
  noHomeworkContent: {
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
    alignItems: 'center',
  },
  noHomeworkText: {
    fontSize: 13,
    color: Colors.gray[400],
    marginBottom: 10,
  },
  addBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 8,
  },
  addBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#fff',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyText: {
    fontSize: 14,
    color: Colors.gray[400],
    marginTop: 12,
    textAlign: 'center',
  },
});
