import { Colors } from '@educard/shared';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  bottomSpacer: { height: 100 },
  centerContent: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    fontSize: 15,
    color: Colors.gray[400],
    marginTop: 12,
  },
  goBackBtn: {
    marginTop: 16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: Colors.primary[500],
  },
  goBackBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  navBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray[100],
  },
  navBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: Colors.gray[50],
  },
  navBtnDisabled: {
    backgroundColor: Colors.gray[50],
  },
  navBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.gray[600],
  },
  navBtnTextDisabled: {
    color: Colors.gray[300],
  },
  content: {
    flex: 1,
    padding: 16,
  },
  studentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  studentAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: Colors.gray[100],
    justifyContent: 'center',
    alignItems: 'center',
  },
  studentInfo: {
    flex: 1,
    marginLeft: 14,
  },
  studentName: {
    fontSize: 16,
    fontWeight: '700',
    color: Colors.gray[800],
  },
  rollNumber: {
    fontSize: 13,
    color: Colors.gray[500],
    marginTop: 2,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    gap: 6,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
  },
  section: {
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.gray[800],
    marginBottom: 10,
  },
  detailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 10,
  },
  detailItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  detailText: {
    fontSize: 13,
    color: Colors.gray[600],
  },
  lateBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#fee2e2',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  lateText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#dc2626',
  },
  notesCard: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 10,
    alignItems: 'flex-start',
  },
  notesText: {
    flex: 1,
    fontSize: 14,
    color: Colors.gray[600],
    lineHeight: 22,
  },
  attachmentCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fff',
    padding: 14,
    borderRadius: 10,
    marginBottom: 8,
  },
  attachmentInfo: {
    flex: 1,
  },
  attachmentName: {
    fontSize: 13,
    fontWeight: '500',
    color: Colors.gray[700],
  },
  attachmentSize: {
    fontSize: 11,
    color: Colors.gray[400],
    marginTop: 2,
  },
  reviewedInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#dcfce7',
    padding: 14,
    borderRadius: 10,
  },
  reviewedText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#166534',
  },
  reviewedDate: {
    fontSize: 11,
    color: '#15803d',
    marginTop: 2,
  },
  feedbackInput: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 14,
    fontSize: 14,
    color: Colors.gray[800],
    minHeight: 100,
    borderWidth: 1,
    borderColor: Colors.gray[200],
  },
  feedbackHint: {
    fontSize: 11,
    color: Colors.gray[400],
    marginTop: 6,
  },
  feedbackReadonly: {
    backgroundColor: Colors.gray[50],
    borderRadius: 10,
    padding: 14,
    minHeight: 80,
  },
  feedbackReadonlyText: {
    fontSize: 14,
    color: Colors.gray[500],
    fontStyle: 'italic',
  },
  permissionNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#fef3c7',
    padding: 14,
    borderRadius: 10,
    marginTop: 8,
  },
  permissionText: {
    flex: 1,
    fontSize: 12,
    color: '#92400e',
  },
  footer: {
    padding: 16,
    paddingBottom: 30,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: Colors.gray[100],
  },
  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary[500],
    paddingVertical: 14,
    borderRadius: 12,
  },
  submitBtnDisabled: {
    opacity: 0.6,
  },
  submitBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  updateBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: Colors.primary[50],
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.primary[200],
  },
  updateBtnText: {
    fontSize: 15,
    fontWeight: '700',
    color: Colors.primary[500],
  },
});
