import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
export const CALENDAR_CELL_SIZE = Math.floor((screenWidth - 80) / 7);

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff7ed' },
  header: { paddingTop: 48, paddingBottom: 20, paddingHorizontal: 16 },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { padding: 4 },
  headerTitle: { color: 'white', fontSize: 20, fontWeight: '700' },
  headerSubtitle: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },
  readOnlyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ede9fe',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 8,
  },
  readOnlyText: { fontSize: 13, fontWeight: '600', color: '#7c3aed' },
  content: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 100 },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    backgroundColor: '#d1fae5',
    borderRadius: 12,
    padding: 14,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#6ee7b7',
  },
  infoText: { flex: 1, fontSize: 13, color: '#065f46', lineHeight: 18 },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  loadingText: { color: '#6b7280', marginTop: 12 },
  section: { marginBottom: 24 },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  sectionHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  sectionTitle: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
  sectionCount: {
    backgroundColor: '#f3f4f6',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  sectionCountText: { fontSize: 12, fontWeight: '600', color: '#6b7280' },
  emptySection: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
  },
  emptySectionText: { color: '#9ca3af', fontSize: 14 },
  exceptionCard: {
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
  },
  forceWorkingCard: { backgroundColor: '#f0fdfa', borderColor: '#99f6e4' },
  forceHolidayCard: { backgroundColor: '#fef2f2', borderColor: '#fecaca' },
  exceptionCardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  exceptionIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forceWorkingIcon: { backgroundColor: '#ccfbf1' },
  forceHolidayIcon: { backgroundColor: '#fee2e2' },
  exceptionInfo: { flex: 1 },
  exceptionDate: { fontSize: 14, fontWeight: '600', color: '#1f2937' },
  exceptionTypeBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginTop: 6,
  },
  forceWorkingBadge: { backgroundColor: '#ccfbf1' },
  forceHolidayBadge: { backgroundColor: '#fee2e2' },
  exceptionTypeText: { fontSize: 11, fontWeight: '600' },
  forceWorkingText: { color: '#0d9488' },
  forceHolidayText: { color: '#dc2626' },
  deleteButton: { padding: 8 },
  exceptionReason: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  exceptionReasonLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 4,
  },
  exceptionReasonText: { fontSize: 13, color: '#374151' },
  exceptionMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  exceptionMetaText: { fontSize: 11, color: '#9ca3af' },
});

export const modalStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  container: {
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  title: { fontSize: 18, fontWeight: '700', color: '#1f2937' },
  body: { padding: 20, maxHeight: 400 },
  bodyContainer: { maxHeight: 400 },
  field: { marginBottom: 20 },
  fieldLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 8,
  },
  dateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  dateButtonText: { fontSize: 14, color: '#1f2937', flex: 1 },
  typeSelector: { gap: 10 },
  typeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 2,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    backgroundColor: '#f9fafb',
  },
  typeOptionSelectedWorking: {
    borderColor: '#0d9488',
    backgroundColor: '#f0fdfa',
  },
  typeOptionSelectedHoliday: {
    borderColor: '#dc2626',
    backgroundColor: '#fef2f2',
  },
  typeOptionText: {
    flex: 1,
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
  },
  typeOptionTextWorking: { color: '#0d9488', fontWeight: '600' },
  typeOptionTextHoliday: { color: '#dc2626', fontWeight: '600' },
  textInput: {
    backgroundColor: '#f9fafb',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: '#1f2937',
    minHeight: 80,
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  switchHint: { fontSize: 12, color: '#9ca3af' },
  classesGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  classChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  classChipSelected: { backgroundColor: '#f0fdfa', borderColor: '#0d9488' },
  classChipText: { fontSize: 13, color: '#6b7280' },
  classChipTextSelected: { color: '#0d9488', fontWeight: '500' },
  noClassesText: { fontSize: 13, color: '#9ca3af', fontStyle: 'italic' },
  actions: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 34,
    borderTopWidth: 1,
    borderTopColor: '#f3f4f6',
  },
  cancelActionButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  cancelActionText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  submitButton: {
    flex: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 10,
  },
  submitButtonWorking: { backgroundColor: '#0d9488' },
  submitButtonHoliday: { backgroundColor: '#dc2626' },
  submitButtonText: { fontSize: 14, fontWeight: '600', color: 'white' },
  // Date Picker
  datePickerContainer: {
    backgroundColor: 'white',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
  },
  datePickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  datePickerTitle: { fontSize: 18, fontWeight: '700', color: '#1f2937' },
  monthNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  monthNavButton: { padding: 8 },
  monthLabel: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
  weekdaysRow: { flexDirection: 'row', marginBottom: 8 },
  weekdayCell: {
    width: CALENDAR_CELL_SIZE,
    alignItems: 'center',
    paddingVertical: 4,
  },
  weekdayText: { fontSize: 12, fontWeight: '600', color: '#6b7280' },
  daysGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: {
    width: CALENDAR_CELL_SIZE,
    height: CALENDAR_CELL_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: CALENDAR_CELL_SIZE / 2,
  },
  selectedDayCell: { backgroundColor: '#10b981' },
  todayCell: { borderWidth: 2, borderColor: '#10b981' },
  dayText: { fontSize: 14, color: '#374151' },
  selectedDayText: { color: 'white', fontWeight: '600' },
  todayText: { color: '#10b981', fontWeight: '600' },
  cancelButton: {
    marginTop: 16,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: '#f3f4f6',
    alignItems: 'center',
  },
  cancelButtonText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },

  // Hoisted (RN CLI no-inline-styles)
  weekdaySunday: { color: '#ef4444' },
  dateButtonPlaceholder: { color: '#9ca3af' },
  dimmed: { opacity: 0.6 },
});
