import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f0fdfa' },
  header: { paddingTop: 48, paddingBottom: 0, paddingHorizontal: 16 },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  backButton: { padding: 4 },
  headerTitle: { color: 'white', fontSize: 20, fontWeight: '700' },
  headerSubtitle: { color: 'rgba(255,255,255,0.8)', fontSize: 13 },

  // Tab Bar
  tabBar: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
  },
  tabActive: { backgroundColor: 'white' },
  tabText: { color: 'rgba(255,255,255,0.8)', fontSize: 14, fontWeight: '600' },
  tabTextActive: { color: '#0d9488' },

  content: { flex: 1 },
  tabContent: { padding: 16, paddingBottom: 100 },

  // Loading/Error States
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  loadingText: { color: '#6b7280', marginTop: 12 },
  errorContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 80,
  },
  errorText: {
    color: '#ef4444',
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
  },
  retryButton: {
    marginTop: 16,
    backgroundColor: '#0d9488',
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderRadius: 8,
  },
  retryButtonText: { color: 'white', fontWeight: '600' },

  // Date Navigation
  dateNavigationBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 8,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  dateNavButton: { padding: 8, borderRadius: 8, backgroundColor: '#f0fdfa' },
  datePickerButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginHorizontal: 8,
    borderRadius: 8,
    backgroundColor: '#f0fdfa',
  },
  datePickerText: { fontSize: 14, fontWeight: '600', color: '#0d9488' },
  todayButton: {
    alignSelf: 'center',
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: '#0d9488',
    borderRadius: 16,
    marginBottom: 12,
  },
  todayButtonText: { color: 'white', fontSize: 12, fontWeight: '600' },

  // Status Bar
  dateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 14,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  dateBarLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  dateIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateLabel: { fontSize: 12, color: '#6b7280' },
  dateValue: { fontSize: 14, fontWeight: '600', color: '#1f2937' },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  holidayBadge: { backgroundColor: '#fef3c7' },
  workingBadge: { backgroundColor: '#dcfce7' },
  nonWorkingBadge: { backgroundColor: '#f3f4f6' },
  holidayBadgeText: { color: '#d97706', fontSize: 12, fontWeight: '600' },
  workingBadgeText: { color: '#16a34a', fontSize: 12, fontWeight: '600' },
  nonWorkingBadgeText: { color: '#6b7280', fontSize: 12, fontWeight: '600' },

  // Banners
  holidayBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#fef3c7',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  holidayBannerTitle: { fontSize: 16, fontWeight: '700', color: '#92400e' },
  holidayBannerName: { fontSize: 13, color: '#a16207', marginTop: 2 },
  nonWorkingBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  nonWorkingBannerTitle: { fontSize: 16, fontWeight: '700', color: '#374151' },
  nonWorkingBannerName: { fontSize: 13, color: '#6b7280', marginTop: 2 },

  // Stats
  statsGrid: { gap: 12, marginBottom: 16 },
  statsRow: { flexDirection: 'row', gap: 12 },
  statsHalf: { flex: 1 },
  statCard: { borderRadius: 12, padding: 14, flex: 1 },
  statCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  statCardTitle: {
    fontSize: 11,
    fontWeight: '500',
    color: '#6b7280',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  statCardValue: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1f2937',
    marginTop: 4,
  },
  statCardSubtitle: { fontSize: 11, color: '#6b7280', marginTop: 2 },
  statCardIconBg: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Overall Card
  overallCard: {
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  overallLabel: {
    color: 'rgba(255,255,255,0.8)',
    fontSize: 13,
    fontWeight: '500',
  },
  overallValue: {
    color: 'white',
    fontSize: 36,
    fontWeight: '700',
    marginTop: 4,
  },

  // Progress Card
  progressCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  progressHeaderLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  progressIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  progressLabel: { fontSize: 15, fontWeight: '600', color: '#1f2937' },
  progressTotal: { fontSize: 13, color: '#6b7280', fontWeight: '500' },
  progressBarContainer: { marginBottom: 8 },
  progressPercentage: { fontSize: 24, fontWeight: '700' },
  progressBarBg: {
    height: 8,
    backgroundColor: '#e5e7eb',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBarFill: { height: '100%', borderRadius: 4 },
  progressStats: { flexDirection: 'row', marginTop: 12, gap: 8 },
  progressStatItem: {
    flex: 1,
    backgroundColor: '#f9fafb',
    borderRadius: 8,
    padding: 10,
    alignItems: 'center',
  },
  progressStatDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 4 },
  progressStatValue: { fontSize: 16, fontWeight: '700', color: '#1f2937' },
  progressStatLabel: { fontSize: 10, color: '#6b7280', marginTop: 2 },

  // Quick Actions
  quickActions: { marginTop: 8 },
  quickActionsTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 14,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  actionButtonIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionButtonText: { flex: 1, marginLeft: 12 },
  actionButtonTitle: { fontSize: 15, fontWeight: '600', color: '#1f2937' },
  actionButtonSubtitle: { fontSize: 12, color: '#6b7280', marginTop: 2 },

  // Report Tab Specific
  selectorCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  selectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  selectorTitle: { fontSize: 15, fontWeight: '600', color: '#374151' },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f9fafb',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 10,
  },
  dropdownText: { flex: 1, fontSize: 14, color: '#374151' },
  dropdownList: {
    marginTop: 8,
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    maxHeight: 200,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  dropdownScroll: { maxHeight: 200 },
  dropdownItem: {
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  dropdownItemSelected: { backgroundColor: '#f0fdfa' },
  dropdownItemText: { fontSize: 14, color: '#374151' },
  dropdownItemTextSelected: { color: '#0d9488', fontWeight: '600' },

  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  monthNavButton: { padding: 8 },
  monthNavCenter: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  monthNavText: { fontSize: 16, fontWeight: '600', color: '#1f2937' },

  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  emptyStateText: { color: '#9ca3af', fontSize: 15, marginTop: 12 },

  summaryCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  summaryTitle: { fontSize: 16, fontWeight: '600', color: '#1f2937' },
  percentageBadge: {
    backgroundColor: '#0d9488',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  percentageText: { color: 'white', fontSize: 14, fontWeight: '700' },
  reportStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statBox: {
    width: '31%',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  statBoxValue: { fontSize: 20, fontWeight: '700' },
  statBoxLabel: { fontSize: 11, color: '#6b7280', marginTop: 4 },

  studentListCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 16,
  },
  studentListTitle: { fontSize: 15, fontWeight: '600', color: '#374151' },
  studentListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  studentListSubtitle: { fontSize: 12, color: '#9ca3af' },
  studentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
  },
  studentRowBorder: { borderBottomWidth: 1, borderBottomColor: '#f3f4f6' },
  studentInfo: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  studentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ccfbf1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  studentAvatarText: { fontSize: 14, fontWeight: '700', color: '#0d9488' },
  studentName: { fontSize: 14, fontWeight: '500', color: '#1f2937', flex: 1 },
  studentMiniStats: { flexDirection: 'row', gap: 8, marginTop: 2 },
  miniStatText: { fontSize: 11, color: '#9ca3af' },
  studentStats: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  studentStatItem: { flexDirection: 'row', alignItems: 'center', gap: 2 },
  studentStatText: { fontSize: 12, color: '#6b7280', fontWeight: '500' },
  studentPercentage: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginLeft: 4,
  },
  studentPercentageLarge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  studentPercentageTextLarge: {
    fontSize: 13,
    fontWeight: '700',
    color: '#374151',
  },
  percentageGreen: { backgroundColor: '#dcfce7' },
  percentageBlue: { backgroundColor: '#dbeafe' },
  percentageYellow: { backgroundColor: '#fef3c7' },
  percentageRed: { backgroundColor: '#fee2e2' },
  studentPercentageText: { fontSize: 11, fontWeight: '700', color: '#374151' },

  // Health Card
  healthCard: { borderRadius: 12, padding: 16, marginBottom: 16 },
  healthHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  healthLeft: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  healthTitle: { fontSize: 16, fontWeight: '700' },
  healthSubtitle: { fontSize: 12, color: '#6b7280', marginTop: 2 },
  healthPercentage: { alignItems: 'flex-end' },
  healthPercentageValue: { fontSize: 28, fontWeight: '700' },

  // Insights Grid
  insightsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  insightBox: { width: '48%', borderRadius: 10, padding: 12 },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 4,
  },
  insightValue: { fontSize: 22, fontWeight: '700' },
  insightLabel: { fontSize: 11, color: '#6b7280' },

  // Action Section
  actionSection: { marginBottom: 16 },
  actionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  actionTitle: { fontSize: 15, fontWeight: '600', color: '#374151' },
  actionCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    flexDirection: 'row',
    gap: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#22c55e',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  actionIcon: {
    width: 40,
    height: 40,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionContent: { flex: 1 },
  actionCardTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1f2937',
    marginBottom: 4,
  },
  actionCardDesc: { fontSize: 12, color: '#6b7280', marginBottom: 8 },
  actionNames: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    alignItems: 'center',
  },
  nameBadge: {
    backgroundColor: '#dcfce7',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  nameBadgeText: { fontSize: 11, color: '#16a34a', fontWeight: '600' },
  moreText: { fontSize: 11, color: '#6b7280' },

  // Critical List
  criticalList: { gap: 6 },
  criticalItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fef2f2',
    padding: 8,
    borderRadius: 8,
  },
  criticalName: { fontSize: 13, color: '#1f2937', flex: 1 },
  criticalBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 12 },
  criticalPercent: { fontSize: 11, fontWeight: '700', color: '#dc2626' },

  // Absentee List
  absenteeList: { gap: 6 },
  absenteeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#fffbeb',
    padding: 8,
    borderRadius: 8,
  },
  absenteeName: { fontSize: 13, color: '#1f2937', flex: 1 },
  absenteeStats: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  absenteeCount: { fontSize: 11, color: '#dc2626', fontWeight: '600' },

  // Half Day List
  halfDayList: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  halfDayItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: '#f0fdfa',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
  },
  halfDayName: { fontSize: 11, color: '#374151' },
  halfDayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: '#fef3c7',
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  halfDayCount: { fontSize: 10, color: '#d97706', fontWeight: '600' },

  // Averages Card
  averagesCard: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  averagesTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  averagesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
  },
  averageItem: { alignItems: 'center' },
  averageValue: { fontSize: 20, fontWeight: '700', color: '#1f2937' },
  averageLabel: { fontSize: 11, color: '#6b7280', marginTop: 4 },
  averageDivider: { width: 1, height: 30, backgroundColor: '#e5e7eb' },

  // Pagination
  paginationInfo: {
    backgroundColor: '#f0fdfa',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  paginationText: { fontSize: 12, color: '#0d9488', fontWeight: '600' },
  loadMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#f0fdfa',
    paddingVertical: 14,
    marginTop: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#99f6e4',
    borderStyle: 'dashed',
  },
  loadMoreText: { fontSize: 14, color: '#0d9488', fontWeight: '600' },

  // Hoisted helpers (RN CLI no-inline-styles: literals must live in the sheet)
  flex1: { flex: 1 },
  zIndex1: { zIndex: 1 },
  zIndex100: { zIndex: 100 },
  zIndex1000: { zIndex: 1000 },
  noClassesText: { color: '#9ca3af', fontSize: 14, paddingVertical: 8 },
  chevronUp: { transform: [{ rotate: '180deg' }] },
  chevronDown: { transform: [{ rotate: '0deg' }] },

  progressStatDotGreen: { backgroundColor: '#22c55e' },
  progressStatDotRed: { backgroundColor: '#ef4444' },
  progressStatDotAmber: { backgroundColor: '#f59e0b' },
  progressStatDotGray: { backgroundColor: '#94a3b8' },

  insightBoxGreen: { backgroundColor: '#dcfce7' },
  insightBoxBlue: { backgroundColor: '#dbeafe' },
  insightBoxAmber: { backgroundColor: '#fef3c7' },
  insightBoxRed: { backgroundColor: '#fee2e2' },
  insightValueGreen: { color: '#16a34a' },
  insightValueBlue: { color: '#2563eb' },
  insightValueAmber: { color: '#d97706' },
  insightValueRed: { color: '#dc2626' },

  actionIconGreen: { backgroundColor: '#dcfce7' },
  actionIconRed: { backgroundColor: '#fee2e2' },
  actionIconAmber: { backgroundColor: '#fef3c7' },
  actionIconTeal: { backgroundColor: '#ccfbf1' },
  actionCardBorderRed: { borderLeftColor: '#ef4444' },
  actionCardBorderAmber: { borderLeftColor: '#f59e0b' },
  actionCardBorderTeal: { borderLeftColor: '#0d9488' },
  actionCardBorderGreen: { borderLeftColor: '#22c55e' },
  actionCardTitleRed: { color: '#dc2626' },
  criticalBadgeBg: { backgroundColor: '#fee2e2' },
  averageValueTeal: { color: '#0d9488' },
});
