import { Colors } from '@educard/shared';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f1f5f9' },
  header: {
    paddingTop: 44,
    paddingBottom: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  circle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  circle2: {
    position: 'absolute',
    bottom: -50,
    left: -30,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  headerContent: { zIndex: 1 },
  topRow: { flexDirection: 'row', alignItems: 'center' },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  titleContainer: { flex: 1 },
  title: { fontSize: 22, fontWeight: '800', color: '#fff' },
  subtitle: { fontSize: 13, color: 'rgba(255,255,255,0.8)', marginTop: 2 },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  readOnlyBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ede9fe',
    paddingVertical: 10,
    paddingHorizontal: 16,
    gap: 8,
  },
  readOnlyText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#7c3aed',
  },
  scrollView: { flex: 1 },
  scrollContent: { padding: 16, paddingBottom: 20 },

  // Hoisted inline-style helpers (no-inline-styles compliance)
  flex1: { flex: 1 },
  bottomSpacer: { height: 200 },
  disabledOpacity: { opacity: 0.6 },
  catIconAmber: { backgroundColor: '#fef3c7' },
  effectiveFromValue: { fontSize: 14, color: Colors.gray[600] },
  noPolicyBox: { padding: 12, alignItems: 'center' },
  noPolicyText: { fontSize: 13, color: Colors.gray[400], textAlign: 'center' },
  childrenWrap: { marginLeft: 16, borderLeftWidth: 2, paddingLeft: 12 },

  // Category card
  categoryCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
    overflow: 'hidden',
  },
  categoryHeader: { flexDirection: 'row', alignItems: 'center', padding: 16 },
  catIconCircle: {
    width: 42,
    height: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  catInfo: { flex: 1, marginLeft: 14 },
  catTitle: { fontSize: 16, fontWeight: '700', color: '#1e293b' },
  catCount: { fontSize: 12, color: Colors.gray[500], marginTop: 2 },

  // Preferences list
  prefList: { paddingHorizontal: 16, paddingBottom: 12 },
  divider: { height: 1, backgroundColor: '#f1f5f9', marginVertical: 4 },

  // Single preference row
  prefRow: { paddingVertical: 12 },
  prefLabelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
    flexWrap: 'wrap',
  },
  prefName: { fontSize: 14, fontWeight: '600', color: '#334155', flex: 1 },

  // Tooltip badge
  tooltipBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#ede9fe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tooltip: {
    backgroundColor: '#faf5ff',
    borderRadius: 10,
    padding: 10,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#ddd6fe',
  },
  tooltipArrow: {
    position: 'absolute',
    top: -5,
    left: 18,
    width: 10,
    height: 10,
    backgroundColor: '#faf5ff',
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderColor: '#ddd6fe',
    transform: [{ rotate: '45deg' }],
  },
  tooltipText: { fontSize: 12, color: '#6b21a8', lineHeight: 17 },

  // Reset link
  resetLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 6,
    alignSelf: 'flex-end',
  },
  resetLinkText: { fontSize: 11, color: Colors.gray[400] },

  // Yes/No pill buttons
  pillRow: { flexDirection: 'row', gap: 8, marginTop: 2 },
  pill: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#e2e8f0',
  },
  pillActiveGreen: { backgroundColor: '#dcfce7', borderColor: '#16a34a' },
  pillActiveRed: { backgroundColor: '#fee2e2', borderColor: '#dc2626' },
  pillActiveBlue: { backgroundColor: '#dbeafe', borderColor: '#2563eb' },
  pillDisabled: { opacity: 0.6 },
  pillText: { fontSize: 14, fontWeight: '600', color: Colors.gray[500] },
  pillTextActive: { color: '#1e293b' },

  // Dropdown
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 4,
  },
  dropdownText: { fontSize: 14, color: '#334155', flex: 1 },

  // Multi-choice chips
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  selectedChip: {
    backgroundColor: '#ede9fe',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  selectedChipText: { fontSize: 12, color: '#7c3aed', fontWeight: '600' },

  // Text input
  textEditRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 4,
  },
  textInput: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 14,
    borderWidth: 1.5,
    borderColor: '#7c3aed',
    color: '#334155',
  },
  textSaveBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#16a34a',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textCancelBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  textValueBox: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    marginTop: 4,
  },
  textValue: { fontSize: 14, color: '#334155' },
  textPlaceholder: { color: Colors.gray[400] },

  // Modals
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingBottom: 40,
    maxHeight: '60%',
  },
  modalHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#cbd5e1',
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1e293b',
    marginBottom: 4,
  },
  modalDesc: {
    fontSize: 13,
    color: Colors.gray[500],
    marginBottom: 12,
    lineHeight: 18,
  },
  modalList: { maxHeight: 300 },
  modalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginBottom: 4,
  },
  modalOptionSelected: { backgroundColor: '#f0fdf4' },
  modalOptionText: { fontSize: 15, color: '#334155', flex: 1 },
  modalOptionTextSelected: { color: '#16a34a', fontWeight: '600' },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#cbd5e1',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  checkboxSelected: { backgroundColor: '#7c3aed', borderColor: '#7c3aed' },
  modalSaveBtn: {
    backgroundColor: '#7c3aed',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 12,
  },
  modalSaveBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },

  emptyContainer: { alignItems: 'center', paddingTop: 80 },
  emptyText: { fontSize: 16, color: Colors.gray[400], marginTop: 12 },
});
