import { StyleSheet } from 'react-native';

export const timetableStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f8fafc' },
  content: { padding: 16, paddingBottom: 32 },
  filterCard: {
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ccfbf1',
    borderRadius: 14,
    padding: 14,
    backgroundColor: '#fff',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  filterLabel: {
    marginBottom: 8,
    fontSize: 12,
    fontWeight: '700',
    color: '#475569',
  },
  dateRow: { flexDirection: 'row', alignItems: 'stretch', gap: 8 },
  dateArrow: {
    width: 42,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#99f6e4',
    borderRadius: 10,
    backgroundColor: '#f0fdfa',
  },
  dateInput: {
    minHeight: 58,
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: '#fff',
  },
  dateTextGroup: { marginLeft: 10, flex: 1 },
  dateDay: { fontSize: 14, fontWeight: '700', color: '#0f172a' },
  dateValue: { marginTop: 2, fontSize: 12, color: '#64748b' },
  todayButton: { alignSelf: 'center', paddingHorizontal: 12, paddingTop: 11 },
  todayButtonText: { fontSize: 12, fontWeight: '700', color: '#0f766e' },
  dayTabs: { paddingTop: 12, gap: 8 },
  dayTab: {
    minWidth: 58,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: '#fff',
  },
  dayTabActive: { backgroundColor: '#6366f1', borderColor: '#6366f1' },
  dayTabShort: { fontSize: 12, fontWeight: '700', color: '#64748b' },
  dayTabFull: { marginTop: 2, fontSize: 10, color: '#94a3b8' },
  dayTabTextActive: { color: '#fff' },
  sectionHeader: { marginBottom: 12 },
  sectionTitle: { fontSize: 17, fontWeight: '800', color: '#0f172a' },
  sectionSubtitle: { marginTop: 3, fontSize: 12, color: '#64748b' },
  dayChip: {
    alignSelf: 'center',
    marginTop: 11,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  holidayChip: { backgroundColor: '#ffe4e6' },
  weekendChip: { backgroundColor: '#e0e7ff' },
  dayChipText: { fontSize: 11, fontWeight: '800' },
  holidayChipText: { color: '#be123c' },
  weekendChipText: { color: '#4338ca' },
  slotCard: {
    marginBottom: 12,
    borderRadius: 12,
    borderLeftWidth: 5,
    padding: 16,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  slotTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  timeText: { fontSize: 12, fontWeight: '600', color: '#475569' },
  statusBadge: {
    maxWidth: '48%',
    borderRadius: 7,
    backgroundColor: 'rgba(255,255,255,0.72)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  statusText: { fontSize: 10, fontWeight: '800', color: '#475569' },
  subjectRow: { flexDirection: 'row', alignItems: 'center' },
  periodNumber: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 11,
  },
  periodNumberText: { fontSize: 13, fontWeight: '800', color: '#fff' },
  subjectVisual: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  subjectVisualImage: { width: 18, height: 18, borderRadius: 4 },
  subjectContent: { flex: 1 },
  subjectText: { fontSize: 16, fontWeight: '700', color: '#1e293b' },
  cancelledSubject: { textDecorationLine: 'line-through', color: '#991b1b' },
  slotLabel: { marginTop: 2, fontSize: 11, color: '#64748b' },
  detailRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  detailText: { flex: 1, fontSize: 12, color: '#64748b' },
  cancelledBadge: { backgroundColor: '#fee2e2' },
  cancelledText: { fontSize: 10, fontWeight: '700', color: '#b91c1c' },
  stateCard: {
    minHeight: 210,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    padding: 24,
    backgroundColor: '#fff',
  },
  errorCard: { borderColor: '#fecaca', backgroundColor: '#fff7f7' },
  holidayCard: { borderColor: '#fecdd3', backgroundColor: '#fff1f2' },
  weekendCard: { borderColor: '#c7d2fe', backgroundColor: '#eef2ff' },
  setupCard: { borderColor: '#fde68a', backgroundColor: '#fffbeb' },
  holidayTitle: { color: '#be123c' },
  weekendTitle: { color: '#4338ca' },
  setupTitle: { color: '#b45309' },
  stateReason: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    color: '#0f172a',
    textAlign: 'center',
  },
  stateTitle: {
    marginTop: 12,
    fontSize: 15,
    fontWeight: '800',
    color: '#1e293b',
    textAlign: 'center',
  },
  stateMessage: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 18,
    color: '#64748b',
    textAlign: 'center',
  },
  retryButton: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    borderRadius: 9,
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: '#0f766e',
  },
  retryButtonText: { fontSize: 12, fontWeight: '800', color: '#fff' },
});
