import { Colors } from '@educard/shared';
import { StyleSheet, type DimensionValue } from 'react-native';

const CALENDAR_CELL_WIDTH: DimensionValue = '14.28%';

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  listContent: { padding: 16, paddingBottom: 100 },

  // Month Navigator
  monthNav: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  monthBtn: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: '#eef2ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  monthCenter: { alignItems: 'center' },
  monthTitle: { fontSize: 20, fontWeight: '800', color: '#1e1b4b' },
  monthSubtitle: {
    fontSize: 12,
    color: '#6366f1',
    fontWeight: '500',
    marginTop: 2,
  },

  // Calendar Card
  calendarCard: {
    marginHorizontal: 16,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#fff',
    shadowColor: '#4f46e5',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: '#e0e7ff',
  },
  calHeaderRow: {
    flexDirection: 'row',
    paddingVertical: 10,
  },
  calHeaderCell: {
    width: CALENDAR_CELL_WIDTH,
    alignItems: 'center',
  },
  calHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
  },
  calHeaderTextSun: { color: '#fca5a5' },
  calGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calCell: {
    width: CALENDAR_CELL_WIDTH,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
    borderBottomWidth: 0.5,
    borderRightWidth: 0.5,
    borderColor: '#f1f5f9',
  },
  calCellEmpty: {
    width: CALENDAR_CELL_WIDTH,
    minHeight: 58,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fafafa',
    borderBottomWidth: 0.5,
    borderRightWidth: 0.5,
    borderColor: '#f1f5f9',
  },
  calCellEmptyText: { fontSize: 12, color: '#d1d5db' },
  calCellToday: {
    borderWidth: 2,
    borderColor: '#4f46e5',
    borderRadius: 4,
  },
  calCellHoliday: { borderWidth: 1.5, borderRadius: 10 },
  calCellSunday: {
    backgroundColor: '#fce7f3',
    borderWidth: 1.5,
    borderColor: '#f9a8d440',
    borderRadius: 10,
  },
  calCellSecondSat: {
    backgroundColor: '#eef2ff',
    borderWidth: 1.5,
    borderColor: '#818cf840',
    borderRadius: 10,
  },
  calCellDay: { fontSize: 14, fontWeight: '600', color: '#374151' },
  calCellDayToday: { color: '#4f46e5', fontWeight: '800', fontSize: 15 },
  calCellDaySunday: { color: '#db2777' },
  calCellDaySecondSat: { color: '#4f46e5', fontWeight: '700' },
  calCellDayHoliday: { fontWeight: '800' },
  calCellBadge: {
    borderRadius: 4,
    paddingHorizontal: 3,
    paddingVertical: 1,
    marginTop: 1,
  },
  calCellBadgeSecondSat: { backgroundColor: '#4f46e518' },
  calCellBadgeText: { fontSize: 7, fontWeight: '700' },
  calCellBadgeTextSecondSat: { color: '#4f46e5' },

  // Legend
  legendCard: {
    marginHorizontal: 16,
    marginTop: 16,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  legendTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.gray[700],
    marginBottom: 10,
  },
  legendGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  legendChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
  },
  legendDot: { width: 8, height: 8, borderRadius: 4 },
  legendChipText: { fontSize: 11, fontWeight: '600' },

  // Upcoming
  upcomingSection: { paddingHorizontal: 16, paddingTop: 20 },
  upcomingSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  upcomingTitle: { fontSize: 16, fontWeight: '700', color: '#1e1b4b' },
  upcomingCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  upcomingCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 8,
  },
  upcomingIcon: { fontSize: 22 },
  upcomingName: { fontSize: 15, fontWeight: '700', color: Colors.gray[800] },
  upcomingDate: { fontSize: 12, color: Colors.gray[500], marginTop: 2 },
  upcomingCardBottom: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  upcomingTypeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  upcomingTypeText: { fontSize: 11, fontWeight: '700' },
  durationBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: '#f1f5f9',
  },
  durationText: { fontSize: 11, fontWeight: '600', color: Colors.gray[600] },

  // Table Card
  tableCard: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
    borderLeftWidth: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  tableCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  tableIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tableCardInfo: { flex: 1, marginLeft: 12 },
  tableCardTitle: { fontSize: 15, fontWeight: '700', color: Colors.gray[800] },
  tableCardDate: { fontSize: 12, color: Colors.gray[500], marginTop: 2 },
  tableCardFooter: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  tinyBtn: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f8fafc',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Empty
  emptyContainer: { alignItems: 'center', paddingTop: 80 },
  emptyText: { fontSize: 16, color: Colors.gray[400], marginTop: 12 },

  // Detail Popup
  popupOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  popupCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    width: '100%',
    maxWidth: 360,
    overflow: 'hidden',
  },
  popupHeader: {
    padding: 20,
    alignItems: 'center',
    gap: 6,
  },
  popupHeaderIcon: { fontSize: 32 },
  popupHeaderDate: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    textAlign: 'center',
  },
  popupItem: { paddingHorizontal: 20, paddingVertical: 12 },
  popupItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  popupItemTitle: { fontSize: 17, fontWeight: '700', color: Colors.gray[800] },
  popupItemDetails: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  popupTypeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  popupTypeText: { fontSize: 12, fontWeight: '600' },
  popupDuration: { fontSize: 12, color: Colors.gray[500] },
  popupDivider: { height: 1, backgroundColor: '#f1f5f9', marginTop: 12 },
  popupActions: {
    flexDirection: 'row',
    padding: 16,
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
  },
  popupEditBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#ede9fe',
  },
  popupEditText: { fontSize: 14, fontWeight: '600', color: '#7c3aed' },
  popupCloseBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#f1f5f9',
  },
  popupCloseText: { fontSize: 14, fontWeight: '600', color: Colors.gray[600] },

  // Form Modal
  formOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  formOverlayContent: { flexGrow: 1, justifyContent: 'center' },
  formCard: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: 40,
    maxHeight: '80%',
  },
  formFields: { maxHeight: 400 },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  formTitle: { fontSize: 18, fontWeight: '700', color: Colors.gray[800] },
  formSubtitle: { fontSize: 13, color: Colors.gray[500], marginTop: 2 },
  formCloseBtn: { padding: 4 },
  formActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  formCancelBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
  },
  formCancelText: { fontSize: 14, fontWeight: '600', color: Colors.gray[600] },
  formSaveBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: '#4f46e5',
    alignItems: 'center',
  },
  formSaveText: { fontSize: 14, fontWeight: '700', color: '#fff' },

  // RN-conversion hoisted styles
  flex1: { flex: 1 },
  iconEmoji: { fontSize: 18 },
  disabledBtn: { opacity: 0.5 },
  scrollContent: { paddingBottom: 100 },
  actionBtnActive: { backgroundColor: 'rgba(255,255,255,0.35)' },
});
